# dirs
display_name: domain13_trained_model
dataset_path_dir: ../dataset_domain/domain13
models_save_dir: domain13_trained_model
output_dir: domain13_evaluation_model

# hyperparams
num_epochs: 300
num_diffusion_iters: 100
num_tests: 100
num_train_demos: 500
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
lr: 0.0001
weight_decay: 0.000001
batch_size: 64
resize_scale: 96
wandb: true

